{
 "title": "Auctions",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "0.5, 0.75, 0.9, 0.95, 0.99, 0.999, 1"
   }
  ]
 },
 "panels": [
  { "title": "Essence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Earth Essence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Rousing Earth\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rousing Earth, {{quantile}}"
    },
    {
     "expr": "auction_price_gold{name=\"Awakened Earth\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Awakened Earth, {{quantile}}"
    }
   ]
  },
  {
   "title": "Ire Essence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Rousing Ire\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rousing Ire, {{quantile}}"
    },
    {
     "expr": "auction_price_gold{name=\"Awakened Ire\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Awakened Ire, {{quantile}}"
    }
   ]
  },
  {
   "title": "Order Essence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Rousing Order\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rousing Order, {{quantile}}"
    },
    {
     "expr": "auction_price_gold{name=\"Awakened Order\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Awakened Order, {{quantile}}"
    }
   ]
  },
  {
   "title": "Decay Essence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Rousing Decay\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rousing Decay, {{quantile}}"
    },
    {
     "expr": "auction_price_gold{name=\"Awakened Decay\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Awakened Decay, {{quantile}}"
    }
   ]
  },
  {
   "title": "Frost Essence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Rousing Frost\", quantile=\"$percentile\"}[60m]   ",
     "legendFormat": "Rousing Frost, {{quantile}}"
    },
    {
     "expr": "auction_price_gold{name=\"Awakened Frost\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Awakened Frost, {{quantile}}"
    }
   ]
  },
  {
   "title": "Fire Essence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Rousing Fire\", quantile=\"$percentile\"}[60m]    ",
     "legendFormat": "Rousing Fire, {{quantile}}"
    },
    {
     "expr": "auction_price_gold{name=\"Awakened Fire\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Awakened Fire, {{quantile}}"
    }
   ]
  },
  { "title": "Mining", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Serevite Ore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Serevite Ore\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rank {{rank}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "Draconium Ore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Draconium Ore\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rank {{rank}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "Khaz'gorite Ore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Khaz'gorite Ore\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rank {{rank}}, {{quantile}}"
    }
   ]
  },
  { "title": "Herbalism", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Hochenblume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Hochenblume\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rank {{rank}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "Hochenblume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Hochenblume\", quantile=\"$percentile\"}",
     "legendFormat": "Rank {{rank}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "Saxifrage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Saxifrage\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rank {{rank}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "Writhebark",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Writhebark\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "Rank {{rank}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "Skinning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resilient Leather",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Resilient Leather\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Adamant Scales",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Adamant Scales\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Dense Hide",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Dense Hide\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Lustrous Scaled Hide",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Lustrous Scaled Hide\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Cacophonous Thunderscale",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Cacophonous Thunderscale\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Crystalspine Fur",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Crystalspine Fur\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Fire-Infused Hide",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Fire-Infused Hide\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Pristine Vorquin Horn",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 11 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Pristine Vorquin Horn\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Rockfang Leather",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Rockfang Leather\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Salamanther Scales",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Salamanther Scales\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Windsong Plumage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Windsong Plumage\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Flawless Proto Dragon Scale",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Flawless Proto Dragon Scale\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  { "title": "Fishing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Scalebelly Mackerel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Scalebelly Mackerel\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Thousandbite Piranha",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 29 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Thousandbite Piranha\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Aileron Seamoth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Aileron Seamoth\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Cerulean Spinefish",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Cerulean Spinefish\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Temporal Dragonhead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Temporal Dragonhead\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Islefin Dorado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 29 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Islefin Dorado\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Magma Thresher",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Magma Thresher\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Prismatic Leaper",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 37 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Prismatic Leaper\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Frosted Rimefin Tuna",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 37 },
   "targets": [
    {
     "expr": "auction_price_gold{name=\"Frosted Rimefin Tuna\", quantile=\"$percentile\"}[60m]",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Enchanting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chromatic Dust",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Chromatic Dust\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Vibrant Shard",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Vibrant Shard\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Resonant Crystal",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Resonant Crystal\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Engineering",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Arclight Capacitor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Arclight Capacitor\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Reinforced Machine Chassis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Reinforced Machine Chassis\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Assorted Safety Fuses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Assorted Safety Fuses\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Everburning Blasting Powder",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Everburning Blasting Powder\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Greased-Up Gears",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Greased-Up Gears\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Shock-Spring Coil",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Shock-Spring Coil\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Handful of Serevite Bolts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Handful of Serevite Bolts\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tailoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tattered Wildercloth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Tattered Wildercloth\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Wildercloth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 2 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Wildercloth\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Frostbitten Wildercloth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Frostbitten Wildercloth\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Decayed Wildercloth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Decayed Wildercloth\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Singed Wildercloth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Singed Wildercloth\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Spool of Wilderthread",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Spool of Wilderthread\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Wildercloth Bolt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Wildercloth Bolt\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Vibrant Wildercloth Bolt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Vibrant Wildercloth Bolt\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Infurious Wildercloth Bolt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Infurious Wildercloth Bolt\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Chronocloth Bolt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Chronocloth Bolt\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Azureweave Bolt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Azureweave Bolt\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Leatherworking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stonecrust Hide",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Stonecrust Hide\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Mireslush Hide",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Mireslush Hide\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Infurious Hide",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Infurious Hide\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Frostbite Scales",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Frostbite Scales\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Earthshine Scales",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Earthshine Scales\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Infurious Scales",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Infurious Scales\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jewelcrafting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eternity Amber",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Eternity Amber\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Mystic Sapphire",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 5 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Mystic Sapphire\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Sundered Onyx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Sundered Onyx\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Vibrant Emerald",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Vibrant Emerald\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Queen's Ruby",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 5 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Queen's Ruby\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Nozdorite",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Nozdorite\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Malygite",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Malygite\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Neltharite",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 13 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Neltharite\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Ysemerald",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 13 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Ysemerald\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Alexstraszite",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Alexstraszite\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Illimited Diamond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 13 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Illimited Diamond\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Crumbled Stone",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 13 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Crumbled Stone\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Fractured Glass",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Fractured Glass\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Silken Gemdust",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 21 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Silken Gemdust\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Shimmering Clasp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Shimmering Clasp\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Glossy Stone",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Glossy Stone\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Frameless Lens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Frameless Lens\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Draconic Vial",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 21 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Draconic Vial\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Empty Soul Cage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Empty Soul Cage\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Elemental Harmony",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 29 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Elemental Harmony\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inscription",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blazing Pigment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Blazing Pigment\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Blazing Ink",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Blazing Ink\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Flourishing Pigment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 6 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Flourishing Pigment\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Flourishing Ink",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Flourishing Ink\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Serene Pigment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 6 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Serene Pigment\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Serene Ink",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Serene Ink\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Burnished Ink",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Burnished Ink\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Cosmic Ink",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Cosmic Ink\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Shimmering Pigment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Shimmering Pigment\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Runed Writhebark",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Runed Writhebark\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Chilled Rune",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 14 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Chilled Rune\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blacksmithing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Primal Molten Alloy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Primal Molten Alloy\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Frostfire Alloy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 7 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Frostfire Alloy\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Infurious Alloy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Infurious Alloy\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Obsidian Seared Alloy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Obsidian Seared Alloy\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alchemy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Primal Convergent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Primal Convergent\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    },
    {
     "title": "Omnium Draconis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
     "targets": [
      {
       "expr": "auction_price_gold{name=\"Omnium Draconis\", quantile=\"$percentile\"}[60m]",
       "legendFormat": "Rank {{rank}}, {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}